# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/shashank/Desktop/CLion-2020.3/clion-2020.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/shashank/Desktop/CLion-2020.3/clion-2020.3/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shashank/Documents/c-linux-sockets-exp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shashank/Documents/c-linux-sockets-exp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/shashank/Desktop/CLion-2020.3/clion-2020.3/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/shashank/Desktop/CLion-2020.3/clion-2020.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shashank/Documents/c-linux-sockets-exp/CMakeFiles /home/shashank/Documents/c-linux-sockets-exp/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shashank/Documents/c-linux-sockets-exp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_linux_sockets_exp

# Build rule for target.
c_linux_sockets_exp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_linux_sockets_exp
.PHONY : c_linux_sockets_exp

# fast build rule for target.
c_linux_sockets_exp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_linux_sockets_exp.dir/build.make CMakeFiles/c_linux_sockets_exp.dir/build
.PHONY : c_linux_sockets_exp/fast

utils/list_adapters.o: utils/list_adapters.c.o

.PHONY : utils/list_adapters.o

# target to build an object file
utils/list_adapters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_linux_sockets_exp.dir/build.make CMakeFiles/c_linux_sockets_exp.dir/utils/list_adapters.c.o
.PHONY : utils/list_adapters.c.o

utils/list_adapters.i: utils/list_adapters.c.i

.PHONY : utils/list_adapters.i

# target to preprocess a source file
utils/list_adapters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_linux_sockets_exp.dir/build.make CMakeFiles/c_linux_sockets_exp.dir/utils/list_adapters.c.i
.PHONY : utils/list_adapters.c.i

utils/list_adapters.s: utils/list_adapters.c.s

.PHONY : utils/list_adapters.s

# target to generate assembly for a file
utils/list_adapters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_linux_sockets_exp.dir/build.make CMakeFiles/c_linux_sockets_exp.dir/utils/list_adapters.c.s
.PHONY : utils/list_adapters.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c_linux_sockets_exp"
	@echo "... utils/list_adapters.o"
	@echo "... utils/list_adapters.i"
	@echo "... utils/list_adapters.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

